Repository Cinimex-Informatica/mq-java-exporter, pull requests merged in 2019-04, with the labels that each got.

#110 Directory for jars renamed
  README.md
  pom.xml
Labels: docs, enhancement

#114 Fixed bug with defining listener status
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
Labels: bug, code, invalid

#117 Endless loop replaced with boolean flag
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
Labels: code, enhancement

#116 Get message timeout added to config file
  README.md
  src/main/java/ru/cinimex/exporter/Config.java
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/resources/exporter_config.yaml
Labels: code, config, enhancement

#118 add extended explanation for using wildcards
  README.md
  src/main/resources/exporter_config.yaml
Labels: config, docs, invalid

#123 README changes
  README.md
Labels: docs, enhancement

#124 add TLS support
  README.md
  src/main/java/ru/cinimex/exporter/Config.java
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQConnection.java
  src/main/java/ru/cinimex/exporter/mq/MQSecurityProperties.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/resources/exporter_config.yaml
Labels: code, config, docs, enhancement

#125 Add new queue-specific metrics, that reflects average size of read messages
  README.md
  src/main/java/ru/cinimex/exporter/prometheus/HTTPServer.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricManagerUtils.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsManager.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
Labels: code, docs, enhancement

#129 Unit tests added
  pom.xml
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFElementRow.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricManagerUtils.java
  src/test/java/ru/cinimex/exporter/ConfigTest.java
  src/test/java/ru/cinimex/exporter/mq/MQConnectionTest.java
  src/test/java/ru/cinimex/exporter/mq/MQObjectTest.java
  src/test/java/ru/cinimex/exporter/mq/MQSecurityPropertiesTest.java
  src/test/java/ru/cinimex/exporter/mq/pcf/PCFClassTest.java
  src/test/java/ru/cinimex/exporter/mq/pcf/PCFDataParserTest.java
  src/test/java/ru/cinimex/exporter/mq/pcf/PCFElementRowTest.java
  src/test/java/ru/cinimex/exporter/mq/pcf/PCFElementTest.java
  src/test/java/ru/cinimex/exporter/mq/pcf/PCFTypeTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/ExtremeGaugeTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/MetricManagerUtilsTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/MetricsManagerTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/MetricsReferenceTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/SimpleCounterTest.java
  src/test/java/ru/cinimex/exporter/prometheus/metrics/SimpleGaugeTest.java
  src/test/java/ru/cinimex/exporter/testutils/Utils.java
  src/test/resources/keystores/keystore.jks
  src/test/resources/keystores/truststore.jks
  src/test/resources/valid_config.yaml
Labels: code, enhancement

#130 ShutdownHook implemented
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/resources/log4j2.properties
Labels: code, enhancement

#132 Add Travis CI integration
  .travis.yml
Labels: config, enhancement
