Repository Cinimex-Informatica/mq-java-exporter, pull requests merged in 2019-03, with the labels that each got.

#37 issue-5 updated metrics type changed
  README.md
Labels: docs

#40 issue15 Resolves: #15. Log4j logging implemented, readme updated with basic configuration file description.
  README.md
  pom.xml
  src/main/java/ru/cinimex/exporter/Config.java
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQConnection.java
  src/main/java/ru/cinimex/exporter/mq/MQObject.java
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFClass.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFDataParser.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFElement.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFType.java
  src/main/java/ru/cinimex/exporter/prometheus/HTTPServer.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsManager.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
  src/main/resources/log4j2.properties
Labels: code, config, docs, enhancement

#41 issue32 Resolves:#32 ExtremeGauges added, typo in readme fixed.
  README.md
  pom.xml
  src/main/java/ru/cinimex/exporter/prometheus/HTTPServer.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/ExtremeGauge.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricInterface.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsManager.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/SimpleCounter.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/SimpleGauge.java
Labels: code, docs, enhancement

#58 issue57 fixed bug with wrong sendPCFCommands flag processing
  .gitignore
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
Labels: awaiting testing, bug, code, config

#48 issue16 Resolves: #16, fixes:#46
  README.md
  pom.xml
Labels: awaiting testing, docs, enhancement

#60 issue44 additional processing for some metrics implemented
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFDataParser.java
Labels: awaiting testing, bug, code

#63 Feature/issue51 rearrange readme structure
  README.md
  docs/images/metric_naming_example_1.png
  docs/images/metric_naming_example_2.png
Labels: awaiting testing, docs, enhancement, invalid

#73 issue62 readme updated with issue #62
  README.md
Labels: bug, docs

#59 Feature/issue7 metric name description resolves #7
  README.md
  docs/images/metric_naming_example_1.png
  docs/images/metric_naming_example_2.png
Labels: docs, enhancement

#65 Feature/issue51 rearrange readme structure
  README.md
Labels: docs, enhancement, invalid

#66 Feature/issue53, issue54, issue47, issue51 wrong subdomain
  README.md
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
Labels: code, docs

#77 issue74 added "STOPPED" status for listener
  README.md
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
Labels: code, docs

#61 issue23 added information about required permissions
  README.md
  src/main/resources/exporter_config.yaml
Labels: config, docs

#92 issue69 Fixes #69
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
Labels: bug, code

#89 issue68 Fixes:#68
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFElement.java
Labels: bug, code

#94 issue70 multiple code smells resolved
  src/main/java/ru/cinimex/exporter/Config.java
  src/main/java/ru/cinimex/exporter/ExporterLauncher.java
  src/main/java/ru/cinimex/exporter/mq/MQConnection.java
  src/main/java/ru/cinimex/exporter/mq/MQObject.java
  src/main/java/ru/cinimex/exporter/mq/MQPCFSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/MQSubscriberManager.java
  src/main/java/ru/cinimex/exporter/mq/MQTopicSubscriber.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFDataParser.java
  src/main/java/ru/cinimex/exporter/mq/pcf/PCFElement.java
  src/main/java/ru/cinimex/exporter/prometheus/HTTPServer.java
  src/main/java/ru/cinimex/exporter/prometheus/Registry.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsManager.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/SimpleCounter.java
  src/main/java/ru/cinimex/exporter/prometheus/metrics/SimpleGauge.java
Labels: bug, code

#96 Link to table of contents was added
  README.md
Labels: docs, invalid

#98 Added queue subdomain in mq domain to readme
  README.md
Labels: bug, docs

#100 Bugfix/issue78 82 83 84 85 86 87 metrics names fixes
  README.md
  src/main/java/ru/cinimex/exporter/prometheus/metrics/MetricsReference.java
Labels: bug, code, docs, invalid

#106 Fixed typo
  README.md
Labels: docs, invalid
